version: '3'
services:
  postgres:
    image: postgis/postgis:13-3.1
    environment:
      POSTGRES_DB: django
      POSTGRES_PASSWORD: postgres
    ports:
      - ${DOCKER_POSTGRES_PORT-5432}:5432
    volumes:
      - dbdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.9.13-management
    ports:
      - ${DOCKER_RABBITMQ_PORT-5672}:5672

  minio:
    image: minio/minio:RELEASE.2022-03-03T21-21-16Z
    # When run with a TTY, minio prints credentials on startup
    tty: true
    command: ["server", "/data", "--console-address", ":${DOCKER_MINIO_CONSOLE_PORT-9001}"]
    environment:
      MINIO_ROOT_USER: minioAccessKey
      MINIO_ROOT_PASSWORD: minioSecretKey
    ports:
      - ${DOCKER_MINIO_PORT-9000}:9000
      - ${DOCKER_MINIO_CONSOLE_PORT-9001}:9001
    volumes:
      - fsdata:/data

volumes:
  dbdata:
  fsdata:
