# Generated by Django 4.0.5 on 2022-06-01 16:24

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rgd', '0009_alter_checksumfile_collection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name='modified'
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                ('command', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                (
                    'entrypoint',
                    models.CharField(blank=True, default=None, max_length=1000, null=True),
                ),
                ('environment', models.JSONField(blank=True, default=dict)),
                ('gpu', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DockerImage',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name='modified'
                    ),
                ),
                ('name', models.CharField(max_length=255, null=True)),
                ('image_id', models.CharField(blank=True, max_length=255, null=True)),
                (
                    'image_file',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='docker_images',
                        to='rgd.checksumfile',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name='modified'
                    ),
                ),
                ('name', models.CharField(max_length=256, unique=True)),
                ('size', models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    'files',
                    models.ManyToManyField(
                        blank=True, related_name='datasets', to='rgd.checksumfile'
                    ),
                ),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AlgorithmTask',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name='modified'
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('created', 'Created but not queued'),
                            ('queued', 'Queued for processing'),
                            ('running', 'Running'),
                            ('failed', 'Failed'),
                            ('success', 'Succeeded'),
                        ],
                        default='queued',
                        max_length=16,
                    ),
                ),
                ('output_log', models.TextField(blank=True, default='', null=True)),
                (
                    'algorithm',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='tasks',
                        to='algorithms.algorithm',
                    ),
                ),
                (
                    'input_dataset',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name='input_tasks',
                        to='algorithms.dataset',
                    ),
                ),
                (
                    'output_dataset',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name='output_tasks',
                        to='algorithms.dataset',
                    ),
                ),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='algorithm',
            name='docker_image',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='workflow_steps',
                to='algorithms.dockerimage',
            ),
        ),
        migrations.AddConstraint(
            model_name='dockerimage',
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(('image_file__isnull', False), ('image_id__isnull', True)),
                    models.Q(
                        ('image_file__isnull', True),
                        ('image_id__isnull', False),
                        ('image_id__length__gt', 0),
                    ),
                    _connector='OR',
                ),
                name='single_image_source',
            ),
        ),
        migrations.AddConstraint(
            model_name='algorithm',
            constraint=models.CheckConstraint(
                check=models.Q(('environment__startswith', '{')), name='only_objects'
            ),
        ),
    ]
