# Generated by Django 3.2.7 on 2021-10-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='gpu',
            field=models.BooleanField(default=False),
        ),
    ]
