# Generated by Django 3.2.7 on 2021-10-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithmtask',
            name='output_log',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
