# Generated by Django 3.2.7 on 2021-10-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0002_alter_algorithmtask_output_log'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='algorithm',
            options={},
        ),
        migrations.AddField(
            model_name='algorithm',
            name='environment',
            field=models.JSONField(default=dict),
        ),
        migrations.AddConstraint(
            model_name='algorithm',
            constraint=models.CheckConstraint(
                check=models.Q(('environment__startswith', '{')), name='only_objects'
            ),
        ),
    ]
