# Generated by Django 3.2.7 on 2021-11-09 21:49

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rgd', '0004_alter_checksumfile_status'),
        ('algorithms', '0002_algorithm_gpu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algorithm',
            name='input_dataset',
        ),
        migrations.RemoveField(
            model_name='algorithmtask',
            name='output_dataset',
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name='modified'
                    ),
                ),
                ('name', models.CharField(max_length=256, unique=True)),
                (
                    'files',
                    models.ManyToManyField(
                        blank=True, related_name='datasets', to='rgd.ChecksumFile'
                    ),
                ),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='algorithmtask',
            name='output_dataset',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name='output_tasks',
                to='algorithms.dataset',
            ),
        ),
        migrations.AddField(
            model_name='algorithmtask',
            name='input_dataset',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name='input_tasks',
                to='algorithms.dataset',
            ),
        ),
    ]
