# Generated by Django 3.2.7 on 2021-11-09 21:49

from django.db import migrations, models
import django.db.models.deletion


def set_default_task_input_dataset(apps, schema_editor):
    AlgorithmTask = apps.get_model('algorithms', 'AlgorithmTask')  # noqa: N806
    Dataset = apps.get_model('algorithms', 'Dataset')  # noqa: N806

    AlgorithmTask.objects.filter(input_dataset=None).update(
        input_dataset=Dataset.objects.get_or_create(name='default_algorithm_task_input_dataset')[0]
    )


def reverse_set_default_task_input_dataset(apps, schema_editor):
    AlgorithmTask = apps.get_model('algorithms', 'AlgorithmTask')  # noqa: N806
    AlgorithmTask.objects.filter(input_dataset__name__endswith='_default_input_dataset').update(
        input_dataset=None
    )


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0003_auto_20211109_2149'),
    ]

    operations = [
        migrations.RunPython(
            set_default_task_input_dataset, reverse_set_default_task_input_dataset
        ),
        migrations.AlterField(
            model_name='algorithmtask',
            name='input_dataset',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name='input_tasks',
                to='algorithms.dataset',
            ),
        ),
    ]
