# Generated by Django 3.2.7 on 2021-10-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0003_auto_20211020_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='entrypoint',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
