# Generated by Django 3.2.9 on 2021-11-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0005_dataset_size'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dockerimage',
            name='single_image_source',
        ),
        migrations.AddConstraint(
            model_name='dockerimage',
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(('image_file__isnull', False), ('image_id__isnull', True)),
                    models.Q(
                        ('image_file__isnull', True),
                        ('image_id__isnull', False),
                        ('image_id__length__gt', 0),
                    ),
                    _connector='OR',
                ),
                name='single_image_source',
            ),
        ),
    ]
