# Generated by Django 3.2.7 on 2021-12-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0006_auto_20211116_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='environment',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='gpu',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
