# Generated by Django 4.0.4 on 2022-05-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0008_alter_algorithm_id_alter_algorithmtask_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithmtask',
            name='command_format_args',
            field=models.JSONField(blank=True, max_length=1000, null=True),
        ),
    ]
