Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "./playbook.yml"
      ansible.galaxy_role_file = "./requirements.yml"
    end

  end
