apiVersion: v1
kind: Pod
metadata:
  name: oasis-worker
spec:
  containers:
    - name: oasis-worker
      image: oasis-worker
      imagePullPolicy: Never
      env:
      - name: DJANGO_CONFIGURATION
        value: DevelopmentConfiguration
      - name: DJANGO_DATABASE_URL
        value: postgres://postgres:postgres@host.minikube.internal:5432/django
      - name: DJANGO_CELERY_BROKER_URL
        value: amqp://host.minikube.internal:5672/
      - name: DJANGO_MINIO_STORAGE_ENDPOINT
        value: host.minikube.internal:9000
      - name: DJANGO_MINIO_STORAGE_ACCESS_KEY
        value: minioAccessKey
      - name: DJANGO_MINIO_STORAGE_SECRET_KEY
        value: minioSecretKey
      - name: DJANGO_STORAGE_BUCKET_NAME
        value: django-storage
  serviceAccountName: job-robot
