apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: job-robot-cluster
subjects:
- kind: ServiceAccount
  name: job-robot
  namespace: default
roleRef:
  kind: ClusterRole
  name: job-robot-cluster
  apiGroup: rbac.authorization.k8s.io
