apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: job-robot
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", ""]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: ["batch", "extensions"]
  resources: ["jobs", "jobs/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
