name: Packer
on:
  push:
    branches:
      - main
    paths:
      - 'infrastructure/ansible/**'
      - 'infrastructure/packer/**'

jobs:
  packer:
    runs-on: ubuntu-latest
    env:
      PACKER_LOG: 1

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Packer
        run: |
          sudo apt-get update
          sudo apt-get -y install packer

      - name: Initialize Packer
        run: packer init .
        working-directory: infrastructure/packer

      - name: Build Artifact
        run: packer build -color=false -on-error=abort .
        working-directory: infrastructure/packer
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
